import{S as d,i as l}from"./assets/vendor-5ObWk2rO.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const s of t.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const u="44405804-89924783490777dc17a96fec8",f="https://pixabay.com/api/?";function m(i){const r=new URLSearchParams({key:u,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0});return fetch(f+r).then(o=>{if(!o.ok)throw new Error(o.status);return o.json()})}const p=new d(".gallery a",{captionsData:"alt",captionDelay:250});function h(i,r){r.innerHTML=y(i),p.refresh()}function y(i){return i.hits.map(({webformatURL:r,largeImageURL:o,tags:a,likes:e,views:t,comments:s,downloads:c})=>`<li>
                <a href="${o}"><img src='${r}' alt='${a}'></a>
                <div class="content">
                    <div class="item"><h3>Likes</h3><p>${e}</p></div>
                    <div class="item"><h3>Views</h3><p>${t}</p></div>
                    <div class="item"><h3>Comments</h3><p>${s}</p></div>
                    <div class="item"><h3>Downloads</h3><p>${c}</p></div>
                </div>
            </li>`).join("")}const n={form:document.forms[0],gallery:document.querySelector(".gallery"),div:document.createElement("div")};n.form.addEventListener("submit",i=>{i.preventDefault(),n.gallery.innerHTML="",g();const r=i.target.query.value.trim();if(!r){n.gallery.innerHTML="",l.warning({title:"Attention!",message:"Search field must not be empty",messageSize:"16",position:"center",close:!1,displayMode:1});return}setTimeout(()=>{m(r).then(o=>{if(console.log(o),!o.hits.length||!o.hits)throw new Error("Error! Nothing to load");h(o,n.gallery)}).catch(()=>{n.gallery.innerHTML="",l.error({title:"Error!",message:"Sorry, there are no images matching your search query. Please try again!",messageSize:"16",backgroundColor:"#ef4040",position:"center",close:!1,displayMode:1})})},2e3)});function g(){n.div.classList.add("loader"),n.gallery.append(n.div)}
//# sourceMappingURL=commonHelpers.js.map
